site_name: DevOps运维开发
site_url: https://hujianli94.github.io
site_author: hujainli94
site_description: >-
  stay hungry,stay foolish

# Repository
repo_name: hujianli94.github.io
repo_url: https://github.com/hujianli94/hujianli94.github.io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 - 2024 hujainli94


# Click to enlarge the image
extra_css:
  - stylesheets/extra.css
  - https://file.cdn.shafish.cn/blog/css/vssue.css
  - https://file.cdn.shafish.cn/blog/css/video-js.min.css
  - https://file.cdn.shafish.cn/blog/css/video.css


extra_javascript:
  - javascripts/extra.js
  - https://file.cdn.shafish.cn/blog/js/video.min.js


# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - tags
  # Display the last modification time of the file
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - comments.md
  - redirects:
      redirect_maps:
        changelog/insiders.md: insiders/changelog.md
        reference/meta-tags.md: reference/index.md
        reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
        sponsorship.md: insiders/index.md
        upgrading.md: upgrade.md
  - minify:
      minify_html: true



# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hujianli94
    - icon: fontawesome/brands/weixin
      link: https://kaliarch-bucket-1251990360.cos.ap-beijing.myqcloud.com/blog_img/20220125122524.png
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1879324764@qq.com>
      name: 发送邮件




  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/hujianli94/hujianli94.github.io/issues/new/?title=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.
# Extensions
markdown_extensions:
  - tables
  - admonition
  - abbr
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.keys
  - markdown.extensions.def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tilde
  - meta
  - def_list
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - english/phonetic_note.md # 英语单词注解统一放在该文件中
      base_path: ["docs/"]
#      check_paths: true
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: hujinali-chaina
      repo: devops-sre
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: 'material'
  language: 'zh'

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png



# Page tree
nav:
  - 首页: index.md
  - Kubernetes:
      - 0.学习线路:
        - Kubernetes/0.学习线路/0.Kubernetes.md
      - 1.安装篇:
        - Kubernetes/1.安装篇/1.Kubeadm安装高可用K8s集群.md
        - Kubernetes/1.安装篇/2.二进制安装高可用K8s集群.md
        - Kubernetes/1.安装篇/3.安装常用工具.md
      - 2.基础篇:
        - Kubernetes/2.基础篇/3.Docker基础.md
        - Kubernetes/2.基础篇/4.Kubernetes的基础概念.md
        - Kubernetes/2.基础篇/5.Kubernetes调度基础.md
        - Kubernetes/2.基础篇/6.Kubernetes服务发布基础.md
        - Kubernetes/2.基础篇/7.Kubernetes配置管理.md
      - 3.进阶篇:
        - Kubernetes/3.进阶篇/8.Kubernetes存储入门.md
        - Kubernetes/3.进阶篇/9.Kubernetes高级调度.md
      - 4.高级篇:
        - Kubernetes/4.高级篇/12.云原生存储Rook.md
        - Kubernetes/4.高级篇/13.中间件容器化.md
      - 5.运维篇:
        - Kubernetes/5.运维篇/14.Kubernetes日志收集.md
        - Kubernetes/5.运维篇/15.Kubernetes监控告警.md
        - Kubernetes/5.运维篇/16.服务发布Ingress进阶.md
      - 6.DevOps篇:
        - Kubernetes/6.DevOps篇/17.DevOps实践.md

  - Docker:
      - 0.学习线路:
        - Docker/0.学习线路/0.Docker.md
      - 1.基础:
        - Docker/1.基础/1.安装Docker.md
        - Docker/1.基础/2.Docker镜像.md
        - Docker/1.基础/3.Docker容器.md
        - Docker/1.基础/4.企业私有仓库harbor.md
        - Docker/1.基础/5.Docker数据.md
        - Docker/1.基础/6.Docker网络.md
        - Docker/1.基础/7.Dockerfile.md
        - Docker/1.基础/8.docker-compose.md
        - Docker/1.基础/9.Docker相关脚本.md
        - Docker/1.基础/10.Docker常用命令.md
      - 2.实战案例:
        - Docker/2.实战案例/1.操作系统.md
        - Docker/2.实战案例/2.Web服务与应用.md
        - Docker/2.实战案例/3.持续开发与管理.md
        - Docker/2.实战案例/4.数据库应用.md
      - 3.Devops:
        - Docker/3.Devops/1.ConfCenter.md
        - Docker/3.Devops/2.CoreDNS.md
        - Docker/3.Devops/3.Harbor.md
        - Docker/3.Devops/4.Python操作Docker.md
        - Docker/3.Devops/5.Haproxy.md
        - Docker/3.Devops/6.Nexus.md

  - Golang:
      - 0.学习线路:
        - Golang/0.学习线路/0.Go-Web开发实战.md
      - 1.Go基础:
        - Golang/1.Go基础/1.安装Go.md
        - Golang/1.Go基础/2.第一个Go程序.md
        - Golang/1.Go基础/3.Go基础语法.md
        - Golang/1.Go基础/4.Go-Module教程.md
      - 2.Go-Web基础:
        - Golang/2.Go-Web基础/5.第一个Go-Web程序.md
        - Golang/2.Go-Web基础/6.Web程序运行原理简介.md
        - Golang/2.Go-Web基础/7.net-http包.md
        - Golang/2.Go-Web基础/8.html-template包.md
      - 3.Go-Web请求处理:
        - Golang/3.Go-Web请求处理/9.简单Web服务器.md
        - Golang/3.Go-Web请求处理/10.处理请求.md
        - Golang/3.Go-Web请求处理/11.session和cookie.md
      - 4.Go访问数据库:
        - Golang/4.Go访问数据库/12.Go操作MySQL.md
        - Golang/4.Go访问数据库/13.Go操作Redis.md
        - Golang/4.Go访问数据库/14.Go操作MongoDB.md
        - Golang/4.Go访问数据库/15.Go的常见ORM库.md
        - Golang/4.Go访问数据库/16.Go操作SQLite.md
      - 5.Go高级网络编程:
        - Golang/5.Go高级网络编程/17.Go-Socket编程.md
        - Golang/5.Go高级网络编程/18.Go-RPC编程.md
        - Golang/5.Go高级网络编程/19.Go-微服务.md
      - 6.Go文件处理:
        - Golang/6.Go文件处理/20.处理目录与文件.md
        - Golang/6.Go文件处理/21.处理XML文件.md
        - Golang/6.Go文件处理/22.处理JSON文件.md
        - Golang/6.Go文件处理/23.处理CSV文件.md
        - Golang/6.Go文件处理/24.处理日志记录.md
        - Golang/6.Go文件处理/25.处理正则表达式.md
        - Golang/6.Go文件处理/26.处理Excel文件.md
      - 7.Go并发编程:
        - Golang/7.Go并发编程/26.并发与并行.md
        - Golang/7.Go并发编程/27.进程 线程和协程.md
        - Golang/7.Go并发编程/28.Go并发模型简介.md
        - Golang/7.Go并发编程/29.gogoroutine和channel实现并发.md
        - Golang/7.Go并发编程/30.sync实现并发.md
        - Golang/7.Go并发编程/31.Go并发的Web应用.md
      - 8.Go标准库:
        - Golang/8.Go标准库/32.time.md
        - Golang/8.Go标准库/33.strings.md
        - Golang/8.Go标准库/34.bytes.md
        - Golang/8.Go标准库/35.json.md
        - Golang/8.Go标准库/36.io-bufio.md
        - Golang/8.Go标准库/37.fmt.md
        - Golang/8.Go标准库/38.strconv.md
        - Golang/8.Go标准库/39.regexp.md
        - Golang/8.Go标准库/40.log.md
        - Golang/8.Go标准库/41.reflect-unsafe.md
        - Golang/8.Go标准库/42.os-path-filepath.md
        - Golang/8.Go标准库/43.unicode.md
        - Golang/8.Go标准库/44.flag.md
        - Golang/8.Go标准库/45.net-url.md
        - Golang/8.Go标准库/46.net-http.md
        - Golang/8.Go标准库/47.sort.md
        - Golang/8.Go标准库/48.errors.md
      - 9.Go三方库:
        - Golang/9.Go三方库/0.开源自己的Go库.md
        - Golang/9.Go三方库/1.cobra.md
        - Golang/9.Go三方库/2.viper.md
        - Golang/9.Go三方库/3.mahonia.md
        - Golang/9.Go三方库/4.ssh.md
        - Golang/9.Go三方库/5.fsnotify.md
        - Golang/9.Go三方库/6.yaml.md
        - Golang/9.Go三方库/7.tail.md
        - Golang/9.Go三方库/8.gopsutil.md
  - Python:
      - 0.学习线路:
        - Python/0.学习线路/0.Pythjon-auto-ops.md
      - 1.基础篇:
        - Python/1.基础篇/1.Python生态工具.md
        - Python/1.基础篇/2.Python第三方库安装.md
        - Python/1.基础篇/3.Python工作环境管理.md
        - Python/1.基础篇/4.VSCode中Python环境配置.md
        - Python/1.基础篇/5.其他开发工具.md
      - 2.高级篇:
        - Python/2.高级篇/6.打造命令行工具.md
        - Python/2.高级篇/7.文本处理.md
        - Python/2.高级篇/8.Linux系统管理.md
        - Python/2.高级篇/9.监控Linux.md


  - Python-vs-Go:
      - 0.学习线路:
        - Python-vs-Go/0.学习线路/0.Python-vs-Go.md
      - 1.对比学习:
        - Python-vs-Go/1.对比学习/1.Hello-World.md
        - Python-vs-Go/1.对比学习/2.Print.md
        - Python-vs-Go/1.对比学习/3.注释.md
        - Python-vs-Go/1.对比学习/4.多行字符串.md
        - Python-vs-Go/1.对比学习/5.Lists.md
        - Python-vs-Go/1.对比学习/6.Map.md
        - Python-vs-Go/1.对比学习/7.Booleans.md
        - Python-vs-Go/1.对比学习/8.Forloop.md
        - Python-vs-Go/1.对比学习/9.Range.md
        - Python-vs-Go/1.对比学习/10.Switch.md
        - Python-vs-Go/1.对比学习/11.可变参数函数.md
        - Python-vs-Go/1.对比学习/12.时间计算.md
        - Python-vs-Go/1.对比学习/13.函数的闭包.md
        - Python-vs-Go/1.对比学习/14.退出处理.md
        - Python-vs-Go/1.对比学习/15.异常捕获.md
        - Python-vs-Go/1.对比学习/16.可变项.md
        - Python-vs-Go/1.对比学习/17.类.md
        - Python-vs-Go/1.对比学习/18.方法.md
        - Python-vs-Go/1.对比学习/19.并发.md
        - Python-vs-Go/1.对比学习/20.Args.md
        - Python-vs-Go/1.对比学习/21.导入模块别名.md
        - Python-vs-Go/1.对比学习/22.字符串格式化.md
        - Python-vs-Go/1.对比学习/23.去重.md
        - Python-vs-Go/1.对比学习/24.带颜色打印.md
      - 2.进阶:
        - Python-vs-Go/2.进阶/1.使用RPC.md
        - Python-vs-Go/2.进阶/2.使用MySQL.md
        - Python-vs-Go/2.进阶/3.使用Redis.md
        - Python-vs-Go/2.进阶/4.使用MongoDB.md
  - Linux:
    - Shell:
      - Linux/shell/Shell简介.md
      - Linux/shell/1.第一个shell程序.md
      - Linux/shell/2.Shell变量.md
      - Linux/shell/3.Shell参数.md
      - Linux/shell/4.Shell数组.md
      - Linux/shell/5.Shell运算符.md
      - Linux/shell/6.Shell echo_printf命令.md
      - Linux/shell/7.Shell test命令.md
      - Linux/shell/8.Shell流程控制.md
      - Linux/shell/9.Shell函数.md
      - Linux/shell/10.Shell输入_输出重定向.md
      - Linux/shell/11.Shell 正则表达式.md
      - Linux/shell/12.Shell 三剑客之grep.md
      - Linux/shell/13.Shell三剑客之sed.md
      - Linux/shell/14.Shell三剑客之awk.md
      - Linux/shell/15.Shell常用工具.md
      - Linux/shell/16.Shell实战项目.md
      - Linux/shell/17.Shell脚本示例.md
      - Linux/shell/18.Shell脚本的参数解析工具.md
      - Linux/shell/19.10个实用Linux-Shell脚本案例.md
      - Linux/shell/20.Shell脚本的规范.md
      - Linux/shell/21.DevOps下的Shell脚本.md
    - Ansible:
        - Linux/Ansible/Ansible-wiki.md
    - git:
        - Linux/git/1.GitHub的高级搜索.md
    - system:
      - Linux/system/0.Linux操作系统镜像下载.md
      - Linux/system/1.Linux系统安全加固最佳实践.md
      - Linux/system/2.Systemd.md
      - Linux/system/3.Superivisor.md
    - serveices:
      - Linux/serveices/0.ubuntu-desktop-vmware.md

