name: ci
on:
  push:
    branches:
      - master
      - main
env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Set up cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: pip install mkdocs-material \
             mkdocs-minify-plugin>=0.3 mkdocs-redirects>=1.0 \
             mkdocs-rss-plugin>=0.17 \
             mkdocs-git-revision-date-localized-plugin

      - name: Deploy
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: mkdocs gh-deploy --force
